import swaggerJsdoc from "swagger-jsdoc";
import enVars from "../config/environment";

const auth = [{ bearerAuth: [] }];
const idParameter = { name: "id", in: "path", required: true, schema: { type: "string" } };
const serviceIdParameter = { name: "serviceId", in: "path", required: true, schema: { type: "string" } };

const successResponse = { description: "Successful response", content: { "application/json": { schema: { $ref: "#/components/schemas/Success" } } } };
const createdResponse = { description: "Created", content: { "application/json": { schema: { $ref: "#/components/schemas/Success" } } } };
const deletedResponse = { description: "Deleted" };
const validationResponse = { description: "Validation error" };
const unauthorizedResponse = { description: "Authentication required" };
const notFoundResponse = { description: "Record not found" };
const jsonBody = (schema: string) => ({ required: true, content: { "application/json": { schema: { $ref: `#/components/schemas/${schema}` } } } });
const multipartBody = (schema: string) => ({ required: true, content: { "multipart/form-data": { schema: { $ref: `#/components/schemas/${schema}` } } } });
const adminResponses = { 400: validationResponse, 401: unauthorizedResponse };
const adminItemResponses = { ...adminResponses, 404: notFoundResponse };

const options = {
  definition: {
    openapi: "3.0.3",
    info: { title: "PureCare Backend API", version: "1.0.0", description: "PureCare platform REST API." },
    servers: [{ url: `http://localhost:${enVars.port}`, description: "Local development" }],
    tags: ["Health", "Auth", "Website", "Services", "FAQs", "Testimonials", "Equipment", "Reservations", "Careers", "Uploads"].map((name) => ({ name })),
    components: {
      securitySchemes: { bearerAuth: { type: "http", scheme: "bearer", bearerFormat: "JWT" } },
      schemas: {
        Success: { type: "object", properties: { success: { type: "boolean", example: true }, data: {} } },
        LoginRequest: { type: "object", required: ["email", "password"], properties: { email: { type: "string", format: "email" }, password: { type: "string", format: "password", minLength: 8 } } },
        SiteGlobalDataRequest: { type: "object", properties: { whatsappNumber: { type: "string", nullable: true }, phoneNumber: { type: "string", nullable: true }, emergencyNumber: { type: "string", nullable: true }, facebookUrl: { type: "string", format: "uri", nullable: true }, instagramUrl: { type: "string", format: "uri", nullable: true }, tiktokUrl: { type: "string", format: "uri", nullable: true }, introVideoUrl: { type: "string", format: "uri", nullable: true } } },
        SiteGlobalData: { allOf: [{ $ref: "#/components/schemas/SiteGlobalDataRequest" }, { type: "object", properties: { id: { type: "string" } } }] },
        Faq: { type: "object", properties: { id: { type: "string" }, questionAr: { type: "string" }, questionEn: { type: "string" }, answerAr: { type: "string" }, answerEn: { type: "string" }, createdAt: { type: "string", format: "date-time" }, updatedAt: { type: "string", format: "date-time" } } },
        FaqCreateRequest: { type: "object", required: ["questionAr", "questionEn", "answerAr", "answerEn"], properties: { questionAr: { type: "string" }, questionEn: { type: "string" }, answerAr: { type: "string" }, answerEn: { type: "string" }, serviceId: { type: "string", nullable: true, description: "Optional service association." } } },
        FaqPatchRequest: { type: "object", properties: { questionAr: { type: "string" }, questionEn: { type: "string" }, answerAr: { type: "string" }, answerEn: { type: "string" } } },
        Testimonial: { type: "object", properties: { id: { type: "string" }, nameAr: { type: "string" }, nameEn: { type: "string" }, gender: { type: "string" }, commentAr: { type: "string" }, commentEn: { type: "string" }, createdAt: { type: "string", format: "date-time" }, updatedAt: { type: "string", format: "date-time" } } },
        TestimonialCreateRequest: { type: "object", required: ["nameAr", "nameEn", "gender", "commentAr", "commentEn"], properties: { nameAr: { type: "string" }, nameEn: { type: "string" }, gender: { type: "string" }, commentAr: { type: "string" }, commentEn: { type: "string" } } },
        TestimonialPatchRequest: { type: "object", properties: { nameAr: { type: "string" }, nameEn: { type: "string" }, gender: { type: "string" }, commentAr: { type: "string" }, commentEn: { type: "string" } } },
        IncludedService: { type: "object", properties: { id: { type: "string" }, serviceId: { type: "string" }, titleAr: { type: "string" }, titleEn: { type: "string" }, descriptionAr: { type: "string" }, descriptionEn: { type: "string" }, iconUrl: { type: "string", format: "uri" } } },
        IncludedServiceCreateRequest: { type: "object", required: ["titleAr", "titleEn", "descriptionAr", "descriptionEn", "icon"], properties: { titleAr: { type: "string" }, titleEn: { type: "string" }, descriptionAr: { type: "string" }, descriptionEn: { type: "string" }, icon: { type: "string", format: "binary" } } },
        IncludedServicePatchRequest: { type: "object", properties: { titleAr: { type: "string" }, titleEn: { type: "string" }, descriptionAr: { type: "string" }, descriptionEn: { type: "string" }, icon: { type: "string", format: "binary" } } },
        TargetedCustomer: { type: "object", properties: { id: { type: "string" }, serviceId: { type: "string" }, titleAr: { type: "string" }, titleEn: { type: "string" }, descriptionAr: { type: "string" }, descriptionEn: { type: "string" }, iconUrl: { type: "string", format: "uri" } } },
        TargetedCustomerCreateRequest: { type: "object", required: ["titleAr", "titleEn", "descriptionAr", "descriptionEn", "icon"], properties: { titleAr: { type: "string" }, titleEn: { type: "string" }, descriptionAr: { type: "string" }, descriptionEn: { type: "string" }, icon: { type: "string", format: "binary" } } },
        TargetedCustomerPatchRequest: { type: "object", properties: { titleAr: { type: "string" }, titleEn: { type: "string" }, descriptionAr: { type: "string" }, descriptionEn: { type: "string" }, icon: { type: "string", format: "binary" } } },
        Service: { type: "object", properties: { id: { type: "string" }, nameAr: { type: "string" }, nameEn: { type: "string" }, descriptionAr: { type: "string" }, descriptionEn: { type: "string" }, imgUrl: { type: "string", format: "uri" }, rate: { type: "number" }, customersCount: { type: "integer" }, responseTime: { type: "string", nullable: true }, faqs: { type: "array", items: { $ref: "#/components/schemas/Faq" } }, included: { type: "array", items: { $ref: "#/components/schemas/IncludedService" } }, targeted: { type: "array", items: { $ref: "#/components/schemas/TargetedCustomer" } } } },
        ServiceCreateRequest: { type: "object", required: ["nameAr", "nameEn", "descriptionAr", "descriptionEn", "rate", "serviceImg"], properties: { nameAr: { type: "string" }, nameEn: { type: "string" }, descriptionAr: { type: "string" }, descriptionEn: { type: "string" }, rate: { type: "number" }, customersCount: { type: "integer" }, responseTime: { type: "string", nullable: true }, serviceImg: { type: "string", format: "binary" } } },
        ServicePatchRequest: { type: "object", properties: { nameAr: { type: "string" }, nameEn: { type: "string" }, descriptionAr: { type: "string" }, descriptionEn: { type: "string" }, rate: { type: "number" }, customersCount: { type: "integer" }, responseTime: { type: "string", nullable: true }, serviceImg: { type: "string", format: "binary" } } },
        ReservationRequest: { type: "object", required: ["fullName", "phoneNumber", "desiredDate", "address"], properties: { fullName: { type: "string" }, phoneNumber: { type: "string" }, age: { type: "integer", minimum: 1, maximum: 120, nullable: true }, desiredDate: { type: "string", format: "date-time" }, address: { type: "string" }, serviceIds: { type: "array", nullable: true, items: { type: "string" }, description: "Optional service IDs." }, healthIssue: { type: "string", nullable: true }, notes: { type: "string", nullable: true } } },
        CareerRequest: { type: "object", required: ["fullName", "phoneNumber", "address", "position", "nationalId"], properties: { fullName: { type: "string" }, phoneNumber: { type: "string" }, age: { type: "integer", minimum: 1, maximum: 120, nullable: true }, yoe: { type: "integer", minimum: 0, maximum: 80, nullable: true }, address: { type: "string" }, position: { type: "string" }, nationalId: { type: "string", format: "binary" }, graduationCertificate: { type: "string", format: "binary" }, professionalLicenseCard: { type: "string", format: "binary" }, workPlaces: { type: "string", nullable: true } } },
        Career: { allOf: [{ $ref: "#/components/schemas/CareerRequest" }, { type: "object", properties: { id: { type: "string" }, createdAt: { type: "string", format: "date-time" } } }] },
        Equipment: { type: "object", properties: { id: { type: "string" }, nameAr: { type: "string" }, nameEn: { type: "string" }, descriptionAr: { type: "string" }, descriptionEn: { type: "string" }, categoryAr: { type: "string" }, categoryEn: { type: "string" }, price: { type: "number" }, imgUrl: { type: "string", format: "uri" }, available: { type: "boolean" } } },
        EquipmentCreateRequest: { type: "object", required: ["nameAr", "nameEn", "descriptionAr", "descriptionEn", "categoryAr", "categoryEn", "price", "equipmentImg"], properties: { nameAr: { type: "string" }, nameEn: { type: "string" }, descriptionAr: { type: "string" }, descriptionEn: { type: "string" }, categoryAr: { type: "string" }, categoryEn: { type: "string" }, price: { type: "number" }, equipmentImg: { type: "string", format: "binary" }, available: { type: "boolean" } } },
        EquipmentPatchRequest: { type: "object", properties: { nameAr: { type: "string" }, nameEn: { type: "string" }, descriptionAr: { type: "string" }, descriptionEn: { type: "string" }, categoryAr: { type: "string" }, categoryEn: { type: "string" }, price: { type: "number" }, equipmentImg: { type: "string", format: "binary" }, available: { type: "boolean" } } },
        UploadDeleteRequest: { type: "object", required: ["mediaUrl"], properties: { mediaUrl: { type: "string", format: "uri" } } },
      },
    },
    paths: {
      "/api/health": { get: { tags: ["Health"], responses: { 200: successResponse } } },
      "/api/auth/login": { post: { tags: ["Auth"], requestBody: jsonBody("LoginRequest"), responses: { 200: successResponse, 400: validationResponse, 401: unauthorizedResponse } } },
      "/api/website-general-data": { get: { tags: ["Website"], responses: { 200: successResponse } }, patch: { tags: ["Website"], security: auth, requestBody: jsonBody("SiteGlobalDataRequest"), responses: { 200: successResponse, ...adminResponses } } },
      "/api/faqs": { get: { tags: ["FAQs"], responses: { 200: successResponse } }, post: { tags: ["FAQs"], security: auth, requestBody: jsonBody("FaqCreateRequest"), responses: { 201: createdResponse, ...adminResponses } } },
      "/api/faqs/{id}": { patch: { tags: ["FAQs"], security: auth, parameters: [idParameter], requestBody: jsonBody("FaqPatchRequest"), responses: { 200: successResponse, ...adminItemResponses } }, delete: { tags: ["FAQs"], security: auth, parameters: [idParameter], responses: { 204: deletedResponse, 401: unauthorizedResponse, 404: notFoundResponse } } },
      "/api/testimonials": { get: { tags: ["Testimonials"], responses: { 200: successResponse } }, post: { tags: ["Testimonials"], security: auth, requestBody: jsonBody("TestimonialCreateRequest"), responses: { 201: createdResponse, ...adminResponses } } },
      "/api/testimonials/{id}": { patch: { tags: ["Testimonials"], security: auth, parameters: [idParameter], requestBody: jsonBody("TestimonialPatchRequest"), responses: { 200: successResponse, ...adminItemResponses } }, delete: { tags: ["Testimonials"], security: auth, parameters: [idParameter], responses: { 204: deletedResponse, 401: unauthorizedResponse, 404: notFoundResponse } } },
      "/api/services": { get: { tags: ["Services"], responses: { 200: successResponse } }, post: { tags: ["Services"], security: auth, requestBody: multipartBody("ServiceCreateRequest"), responses: { 201: createdResponse, ...adminResponses } } },
      "/api/services/{id}": { get: { tags: ["Services"], parameters: [idParameter], responses: { 200: successResponse, 404: notFoundResponse } }, patch: { tags: ["Services"], security: auth, parameters: [idParameter], requestBody: multipartBody("ServicePatchRequest"), responses: { 200: successResponse, ...adminItemResponses } }, delete: { tags: ["Services"], security: auth, parameters: [idParameter], responses: { 204: deletedResponse, 401: unauthorizedResponse, 404: notFoundResponse } } },
      "/api/services/{serviceId}/included-services": { post: { tags: ["Services"], security: auth, parameters: [serviceIdParameter], requestBody: multipartBody("IncludedServiceCreateRequest"), responses: { 201: createdResponse, ...adminResponses } } },
      "/api/services/{serviceId}/included-services/{id}": { patch: { tags: ["Services"], security: auth, parameters: [serviceIdParameter, idParameter], requestBody: multipartBody("IncludedServicePatchRequest"), responses: { 200: successResponse, ...adminItemResponses } }, delete: { tags: ["Services"], security: auth, parameters: [serviceIdParameter, idParameter], responses: { 204: deletedResponse, 401: unauthorizedResponse, 404: notFoundResponse } } },
      "/api/services/{serviceId}/targeted-customers": { post: { tags: ["Services"], security: auth, parameters: [serviceIdParameter], requestBody: multipartBody("TargetedCustomerCreateRequest"), responses: { 201: createdResponse, ...adminResponses } } },
      "/api/services/{serviceId}/targeted-customers/{id}": { patch: { tags: ["Services"], security: auth, parameters: [serviceIdParameter, idParameter], requestBody: multipartBody("TargetedCustomerPatchRequest"), responses: { 200: successResponse, ...adminItemResponses } }, delete: { tags: ["Services"], security: auth, parameters: [serviceIdParameter, idParameter], responses: { 204: deletedResponse, 401: unauthorizedResponse, 404: notFoundResponse } } },
      "/api/equipment": { get: { tags: ["Equipment"], parameters: [{ name: "page", in: "query", schema: { type: "integer", minimum: 1, default: 1 } }, { name: "limit", in: "query", schema: { type: "integer", minimum: 1, maximum: 100, default: 20 } }, { name: "search", in: "query", description: "Case-insensitive partial search across Arabic and English names and descriptions.", schema: { type: "string" } }, { name: "category", in: "query", description: "Exact case-insensitive match against Arabic or English category.", schema: { type: "string" } }, { name: "minPrice", in: "query", schema: { type: "number", minimum: 0 } }, { name: "maxPrice", in: "query", schema: { type: "number", minimum: 0 } }], responses: { 200: successResponse, 400: validationResponse } }, post: { tags: ["Equipment"], security: auth, requestBody: multipartBody("EquipmentCreateRequest"), responses: { 201: createdResponse, ...adminResponses } } },
      "/api/equipment/{id}": { patch: { tags: ["Equipment"], security: auth, parameters: [idParameter], requestBody: multipartBody("EquipmentPatchRequest"), responses: { 200: successResponse, ...adminItemResponses } }, delete: { tags: ["Equipment"], security: auth, parameters: [idParameter], responses: { 204: deletedResponse, 401: unauthorizedResponse, 404: notFoundResponse } } },
      "/api/reservations": { post: { tags: ["Reservations"], requestBody: jsonBody("ReservationRequest"), responses: { 201: createdResponse, 400: validationResponse } }, get: { tags: ["Reservations"], security: auth, responses: { 200: successResponse, 401: unauthorizedResponse } } },
      "/api/careers": { post: { tags: ["Careers"], requestBody: multipartBody("CareerRequest"), responses: { 201: createdResponse, 400: validationResponse } }, get: { tags: ["Careers"], security: auth, responses: { 200: successResponse, 401: unauthorizedResponse } } },
      "/api/careers/{id}": { delete: { tags: ["Careers"], security: auth, parameters: [idParameter], responses: { 204: deletedResponse, 401: unauthorizedResponse, 404: notFoundResponse } } },
      "/api/uploads": { post: { tags: ["Uploads"], security: auth, requestBody: { required: true, content: { "multipart/form-data": { schema: { type: "object", required: ["file"], properties: { file: { type: "string", format: "binary" }, mediaUrl: { type: "string", format: "uri", nullable: true, description: "Existing Cloudinary URL to replace." } } } } } }, responses: { 201: createdResponse, ...adminResponses } }, delete: { tags: ["Uploads"], security: auth, requestBody: jsonBody("UploadDeleteRequest"), responses: { 204: deletedResponse, ...adminItemResponses } } },
    },
  },
  apis: [],
};

const API_SPECS = swaggerJsdoc(options);

export default API_SPECS;
